# Generated by Django 2.2.6 on 2019-10-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0002_auto_20191029_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='description',
        ),
    ]
