# Generated by Django 2.2.6 on 2019-11-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0004_auto_20191101_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited', to='question_box.Question'),
        ),
    ]
