# Generated by Django 2.2.6 on 2019-11-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0005_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
    ]
