# Generated by Django 2.2.6 on 2019-11-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0005_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
