# Generated by Django 2.2.6 on 2019-11-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0006_remove_user_favorites'),
        ('question_box', '0007_auto_20191103_2036'),
    ]

    operations = [
    ]
