# Generated by Django 2.2.6 on 2019-11-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0008_merge_20191103_2352'),
        ('question_box', '0008_merge_20191104_1922'),
        ('question_box', '0009_auto_20191104_0211'),
    ]

    operations = [
    ]
