# Generated by Django 2.2.6 on 2019-11-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0010_merge_20191104_1942'),
        ('question_box', '0006_auto_20191104_0101'),
    ]

    operations = [
    ]
